const PB_URL='http://127.0.0.1:8090',OWNER='chmzino5e3lqgca';
async function getToken(){const r=await fetch(`${PB_URL}/api/collections/_superusers/auth-with-password`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identity:'whatnico007@gmail.com',password:'Pocketbasemerda1'})});return(await r.json()).token;}
const Q=[
  // ── Alto Medioevo ─────────────────────────────────────────────────
  {s:'Medioevo',t:'Alto Medioevo',b:'remember',c:'In quale anno Carlo Magno fu incoronato imperatore del Sacro Romano Impero?',o:['800','768','843','962'],a:'800'},
  {s:'Medioevo',t:'Alto Medioevo',b:'remember',c:'Da quale regione provenivano i Vichinghi che razziarono le coste europee tra VIII e X secolo?',o:['Scandinavia (Norvegia, Danimarca, Svezia)','Russia meridionale','Isole britanniche','Germania settentrionale'],a:'Scandinavia (Norvegia, Danimarca, Svezia)'},
  {s:'Medioevo',t:'Alto Medioevo',b:'understand',c:'Perché la caduta dell\'Impero Romano d\'Occidente (476) non significò una rottura immediata e totale con la civiltà romana?',o:['I regni barbarici adottarono molte strutture romane: diritto, lingua latina, Chiesa, e collaborarono con l\'aristocrazia romana superstite','I Romani sconfissero i Barbari e ripresero il controllo entro un secolo','La cultura barbarica era superiore e sostituì rapidamente quella romana','Roma rimase capitale politica anche dopo il 476'],a:'I regni barbarici adottarono molte strutture romane: diritto, lingua latina, Chiesa, e collaborarono con l\'aristocrazia romana superstite'},
  {s:'Medioevo',t:'Alto Medioevo',b:'understand',c:'Cosa spiega la straordinaria rapidità dell\'espansione islamica nel VII-VIII secolo dall\'Arabia all\'Iberia?',o:['La forza militare, un messaggio religioso unificante, la debolezza dei vicini (Bisanzio esausto, Persia crollata) e la motivazione dei guerrieri','Solo la superiorità militare degli eserciti arabi rispetto a tutti i vicini','La conversione volontaria e pacifica di tutte le popolazioni conquistate','L\'accordo diplomatico tra il Califfo e i re europei'],a:'La forza militare, un messaggio religioso unificante, la debolezza dei vicini (Bisanzio esausto, Persia crollata) e la motivazione dei guerrieri'},
  {s:'Medioevo',t:'Alto Medioevo',b:'apply',c:'Un re barbaro vuole ottenere la cooperazione della popolazione romana nel suo nuovo regno. Quale strategia adotta?',o:['Si converte al Cristianesimo e collabora con la Chiesa e l\'aristocrazia romana (come fece Clodoveo dei Franchi)','Impone la lingua barbara e abolisce tutte le leggi romane','Spogli tutte le chiese e distribuisce i beni ai guerrieri','Si dichiara nuovo imperatore romano con piena autorità'],a:'Si converte al Cristianesimo e collabora con la Chiesa e l\'aristocrazia romana (come fece Clodoveo dei Franchi)'},
  {s:'Medioevo',t:'Alto Medioevo',b:'apply',c:'Un monaco benedettino del IX secolo deve copiare un testo antico nello scriptorium. Quale materiale e strumento usa?',o:['Pergamena di pelle animale, penna d\'oca e inchiostro fatto con resine e nerofumo','Papiro importato dall\'Egitto con pennello di canna','Carta prodotta localmente con inchiostro di china','Tavolette di cera con stilo metallico'],a:'Pergamena di pelle animale, penna d\'oca e inchiostro fatto con resine e nerofumo'},
  {s:'Medioevo',t:'Alto Medioevo',b:'analyze',c:'Quali fattori spiegano la sopravvivenza dell\'Impero Romano d\'Oriente (Bisanzio) per altri mille anni dopo la caduta dell\'Occidente?',o:['Posizione geografica difendibile di Costantinopoli, controllo del commercio orientale, forte burocrazia professionale e identità greco-cristiana coesa','La superiorità militare assoluta dell\'esercito bizantino','Un accordo segreto con i popoli barbarici che la proteggevano','L\'abbondanza di oro che permetteva di pagare qualsiasi esercito nemico'],a:'Posizione geografica difendibile di Costantinopoli, controllo del commercio orientale, forte burocrazia professionale e identità greco-cristiana coesa'},
  {s:'Medioevo',t:'Alto Medioevo',b:'analyze',c:'Confrontando il governo carolingio con quello dei regni romano-barbarici precedenti, quale cambiamento emerge?',o:['Carlo Magno tentò di ricostruire un\'amministrazione centralizzata con i missi dominici, una riforma culturale (Rinascita carolingia) e un sistema legale più uniforme','Il governo carolingio era identico ai regni barbarici precedenti, senza innovazioni','Carlo Magno abolì completamente le strutture locali e governò direttamente ogni villaggio','Il governo carolingio era più decentralizzato di quello romano-barbarico'],a:'Carlo Magno tentò di ricostruire un\'amministrazione centralizzata con i missi dominici, una riforma culturale (Rinascita carolingia) e un sistema legale più uniforme'},
  {s:'Medioevo',t:'Alto Medioevo',b:'evaluate',c:'La Rinascita carolingia fu una vera rinascita culturale o principalmente propaganda imperiale?',o:['Ebbe un reale impatto culturale (scriptoria, scuole palatine, standardizzazione del latino) ma rimase limitata alle élite e non cambiò la vita della maggioranza','Fu puramente propaganda senza alcun impatto concreto sulla cultura','Trasformò radicalmente la cultura di tutta la popolazione europea','Fu più importante della stessa Rinascita italiana del XV secolo'],a:'Ebbe un reale impatto culturale (scriptoria, scuole palatine, standardizzazione del latino) ma rimase limitata alle élite e non cambiò la vita della maggioranza'},
  {s:'Medioevo',t:'Alto Medioevo',b:'create',c:'Se l\'avanzata islamica non si fosse fermata a Poitiers nel 732, come avrebbe potuto cambiare l\'Europa medievale?',o:['Possibile islamizzazione dell\'Europa occidentale con profonde conseguenze religiose, linguistiche e culturali, simile a quanto avvenne in Spagna e Nord Africa','L\'Europa sarebbe rimasta cristiana grazie alla resistenza spontanea della popolazione','I Franchi avrebbero comunque vinto in una battaglia successiva','L\'Islam si sarebbe fermato comunque alle Alpi per ragioni climatiche'],a:'Possibile islamizzazione dell\'Europa occidentale con profonde conseguenze religiose, linguistiche e culturali, simile a quanto avvenne in Spagna e Nord Africa'},

  // ── Feudalesimo ───────────────────────────────────────────────────
  {s:'Medioevo',t:'Feudalesimo',b:'remember',c:'Come si chiamava il rito con cui un signore concedeva formalmente terre e poteri a un vassallo?',o:['Investitura feudale','Battesimo','Consacrazione vescovile','Incoronazione reale'],a:'Investitura feudale'},
  {s:'Medioevo',t:'Feudalesimo',b:'remember',c:'Chi erano i servi della gleba nel sistema feudale medievale?',o:['Contadini legati alla terra che non potevano abbandonarla senza il permesso del signore','Soldati professionisti al servizio del re','Monaci che lavoravano nei campi dei monasteri','Artigiani urbani dipendenti dai mercanti'],a:'Contadini legati alla terra che non potevano abbandonarla senza il permesso del signore'},
  {s:'Medioevo',t:'Feudalesimo',b:'understand',c:'Perché il sistema feudale si sviluppò nell\'Europa post-carolingia del IX-X secolo?',o:['Il crollo dell\'autorità centrale dopo la divisione dell\'impero carolingio costrinse le popolazioni a cercare protezione locale dai signori in cambio di obbedienza e lavoro','Fu imposto dai re come sistema di controllo deliberato della popolazione','Si sviluppò per imitazione del modello dell\'Impero Romano','Fu una scelta volontaria dei contadini che preferivano la protezione alla libertà'],a:'Il crollo dell\'autorità centrale dopo la divisione dell\'impero carolingio costrinse le popolazioni a cercare protezione locale dai signori in cambio di obbedienza e lavoro'},
  {s:'Medioevo',t:'Feudalesimo',b:'understand',c:'Come funzionava nella pratica la gerarchia feudale dal re al servo della gleba?',o:['Catena di fedeltà e obblighi reciproci: il re concedeva feudi ai grandi signori, che li subinfeudavano a cavalieri, che controllavano i contadini','Una struttura flat dove tutti i signori dipendevano direttamente dal re','Un sistema dove i vescovi gestivano tutti i feudi per conto del re','I servi eleggevano i loro signori e potevano destituirli'],a:'Catena di fedeltà e obblighi reciproci: il re concedeva feudi ai grandi signori, che li subinfeudavano a cavalieri, che controllavano i contadini'},
  {s:'Medioevo',t:'Feudalesimo',b:'apply',c:'Un contadino medievale vuole trasferirsi in una città vicina per lavorare come artigiano. Quale ostacolo incontra?',o:['È un servo della gleba e non può lasciare la terra senza il consenso scritto del suo signore feudale','È libero di muoversi: i servi della gleba potevano andare dove volevano','Deve pagare solo una tassa di trasferimento al re','Basta avvisare il parroco del villaggio'],a:'È un servo della gleba e non può lasciare la terra senza il consenso scritto del suo signore feudale'},
  {s:'Medioevo',t:'Feudalesimo',b:'apply',c:'Un cavaliere medievale ha ricevuto un feudo in cambio di servizio militare. Qual è il suo principale obbligo verso il signore?',o:['Prestare servizio militare armato per un periodo stabilito (generalmente 40 giorni l\'anno) quando chiamato','Pagare ogni anno un terzo del raccolto del feudo','Costruire e mantenere le strade del territorio del signore','Educare i figli del signore nelle arti cavalleresche'],a:'Prestare servizio militare armato per un periodo stabilito (generalmente 40 giorni l\'anno) quando chiamato'},
  {s:'Medioevo',t:'Feudalesimo',b:'analyze',c:'Quali fattori causarono il declino del feudalesimo tra il XII e il XIV secolo?',o:['La rinascita delle città e del commercio monetario, il rafforzamento delle monarchie centrali e la Peste nera che distrusse il legame servo-terra','Solo la Peste nera, che uccise troppi signori per mantenere il sistema','Le invasioni mongole che distrussero la struttura feudale','Una deliberata riforma dei re che abolirono il feudalesimo per aumentare il proprio potere'],a:'La rinascita delle città e del commercio monetario, il rafforzamento delle monarchie centrali e la Peste nera che distrusse il legame servo-terra'},
  {s:'Medioevo',t:'Feudalesimo',b:'analyze',c:'Quali differenze e analogie esistono tra il feudalesimo europeo medievale e il sistema dei samurai in Giappone?',o:['Entrambi basati su fedeltà personale guerriera e concessione di terre, ma con differenze culturali, religiose e giuridiche: il Bushido giapponese era più codificato del codice cavalleresco europeo','Erano sistemi identici, importati dal Giappone in Europa attraverso le Crociate','Il sistema giapponese era basato solo sulla religione, quello europeo solo sull\'economia','Non ci sono analogie: i due sistemi erano completamente diversi'],a:'Entrambi basati su fedeltà personale guerriera e concessione di terre, ma con differenze culturali, religiose e giuridiche: il Bushido giapponese era più codificato del codice cavalleresco europeo'},
  {s:'Medioevo',t:'Feudalesimo',b:'evaluate',c:'Il sistema feudale fu una risposta efficace all\'instabilità politica del Medioevo?',o:['Sì per la protezione locale che garantiva in assenza di autorità centrale, ma creava frammentazione del potere, oppressione dei contadini e conflitti tra signori','No: fu un fallimento totale che non garantì mai alcuna protezione','Sì: fu la migliore forma di governo mai inventata nella storia europea','No: era inutile perché le città erano già in grado di difendersi da sole'],a:'Sì per la protezione locale che garantiva in assenza di autorità centrale, ma creava frammentazione del potere, oppressione dei contadini e conflitti tra signori'},
  {s:'Medioevo',t:'Feudalesimo',b:'create',c:'Se la Magna Carta (1215) non fosse mai stata firmata dal re Giovanni d\'Inghilterra, come si sarebbe potuta sviluppare la monarchia inglese?',o:['Probabilmente verso un assolutismo simile a quello francese del XVII sec., senza le premesse giuridiche del parlamentarismo e della common law moderna','Verso una repubblica democratica anticipatrice della Rivoluzione americana','Verso una monarchia teocratica controllata dalla Chiesa','Non avrebbe avuto alcun effetto: la Magna Carta era solo simbolica'],a:'Probabilmente verso un assolutismo simile a quello francese del XVII sec., senza le premesse giuridiche del parlamentarismo e della common law moderna'},

  // ── Crociate ──────────────────────────────────────────────────────
  {s:'Medioevo',t:'Crociate',b:'remember',c:'Chi indisse la Prima Crociata nel 1095 al Concilio di Clermont?',o:['Papa Urbano II','Papa Gregorio VII','L\'imperatore Enrico IV','Il re di Francia Filippo I'],a:'Papa Urbano II'},
  {s:'Medioevo',t:'Crociate',b:'remember',c:'In quale anno Saladino (Salah ad-Din) riconquistò Gerusalemme dai Crociati?',o:['1187','1099','1204','1291'],a:'1187'},
  {s:'Medioevo',t:'Crociate',b:'understand',c:'Perché i crociati erano motivati a partecipare alle costose e pericolose spedizioni in Terrasanta?',o:['Motivazioni religiose (indulgenza plenaria, salvezza dell\'anima) combinate con aspettative economiche di bottino e terre, e motivazioni politiche','Solo motivazioni religiose: erano tutti santi convinti','Solo motivi economici: cercavano ricchezze nell\'Oriente','Il Papa ordinava la partecipazione sotto pena di morte'],a:'Motivazioni religiose (indulgenza plenaria, salvezza dell\'anima) combinate con aspettative economiche di bottino e terre, e motivazioni politiche'},
  {s:'Medioevo',t:'Crociate',b:'understand',c:'Come mai la Quarta Crociata (1204) deviò verso Costantinopoli invece di raggiungere Gerusalemme?',o:['Gli interessi commerciali di Venezia (creditrice dei crociati) portarono al saccheggio della città cristiana rivale','I crociati si persero e raggiunsero Costantinopoli per sbaglio','Il Papa ordinò espressamente di attaccare Bisanzio','Saladino aveva già liberato Gerusalemme, rendendo la crociata inutile'],a:'Gli interessi commerciali di Venezia (creditrice dei crociati) portarono al saccheggio della città cristiana rivale'},
  {s:'Medioevo',t:'Crociate',b:'apply',c:'Un cavaliere crociato del XII sec. vuole partecipare alla crociata ma non ha fondi. Quale soluzione pratica adotta?',o:['Cede temporaneamente le sue terre in pegno a un monastero o a un mercante in cambio del denaro necessario all\'equipaggiamento','Rinuncia alla crociata: senza denaro era impossibile partecipare','Chiede un prestito direttamente al Papa','Si unisce come servo non combattente di un nobile crociato più ricco'],a:'Cede temporaneamente le sue terre in pegno a un monastero o a un mercante in cambio del denaro necessario all\'equipaggiamento'},
  {s:'Medioevo',t:'Crociate',b:'apply',c:'Federico II di Svevia recuperò Gerusalemme nel 1229 senza combattere. Quale metodo usò?',o:['Una trattativa diplomatica con il sultano al-Kamil d\'Egitto, ottenendo un accordo decennale sulla città','Un assedio di tre anni che costrinse la città alla resa','Un attacco a sorpresa notturno con pochi cavalieri d\'élite','Un miracolo religioso che spaventò i difensori'],a:'Una trattativa diplomatica con il sultano al-Kamil d\'Egitto, ottenendo un accordo decennale sulla città'},
  {s:'Medioevo',t:'Crociate',b:'analyze',c:'Quali effetti ebbero le Crociate sugli scambi culturali tra Europa cristiana e mondo islamico?',o:['Trasmissione di conoscenze scientifiche arabe (matematica, medicina, filosofia aristotelica), prodotti (spezie, cotone, carta) e tecnologie militari verso l\'Europa','Le Crociate bloccarono qualsiasi scambio culturale per secoli','Solo effetti negativi: aumentarono il fanatismo religioso senza alcun trasferimento culturale','Le Crociate portarono la cultura europea in Oriente, non viceversa'],a:'Trasmissione di conoscenze scientifiche arabe (matematica, medicina, filosofia aristotelica), prodotti (spezie, cotone, carta) e tecnologie militari verso l\'Europa'},
  {s:'Medioevo',t:'Crociate',b:'analyze',c:'Perché le Crociate fallirono nell\'obiettivo di mantenere stabilmente Gerusalemme cristiana?',o:['Mancanza di unità politica tra i crociati, distanza logistica insostenibile dall\'Europa e la progressiva riorganizzazione politico-militare del mondo islamico (Saladino, Mamelucci)','Il clima caldo della Terrasanta rendeva impossibile la vita ai cavalieri europei','Il Papa ritirò il sostegno alle crociate dopo la Prima','Gli Ordini militari erano troppo corrotti per difendere i territori'],a:'Mancanza di unità politica tra i crociati, distanza logistica insostenibile dall\'Europa e la progressiva riorganizzazione politico-militare del mondo islamico (Saladino, Mamelucci)'},
  {s:'Medioevo',t:'Crociate',b:'evaluate',c:'Le Crociate furono un fallimento storico o produssero effetti positivi per l\'Europa?',o:['Fallirono militarmente nel loro obiettivo principale, ma accelerarono gli scambi commerciali e culturali con l\'Oriente che contribuirono al Rinascimento europeo','Furono un successo totale: Gerusalemme rimase cristiana per secoli','Furono un fallimento totale senza alcun effetto positivo per l\'Europa','Furono positive solo per Venezia e Genova, non per il resto dell\'Europa'],a:'Fallirono militarmente nel loro obiettivo principale, ma accelerarono gli scambi commerciali e culturali con l\'Oriente che contribuirono al Rinascimento europeo'},
  {s:'Medioevo',t:'Crociate',b:'create',c:'Se le Crociate non fossero mai avvenute, come sarebbe cambiato il rapporto tra Europa cristiana e mondo islamico nel Medioevo?',o:['Maggiore isolamento reciproco con ritardo nel recupero delle conoscenze classiche attraverso il mondo arabo e forse minore ostilità strutturale tra le due civiltà','Le due civiltà si sarebbero comunque scontrate in una guerra ancora più grande','L\'Islam avrebbe conquistato tutta l\'Europa senza la resistenza crociata','Il commercio mediterraneo sarebbe stato impossibile senza le Crociate'],a:'Maggiore isolamento reciproco con ritardo nel recupero delle conoscenze classiche attraverso il mondo arabo e forse minore ostilità strutturale tra le due civiltà'},

  // ── Basso Medioevo ────────────────────────────────────────────────
  {s:'Medioevo',t:'Basso Medioevo',b:'remember',c:'In quale anno cadde Costantinopoli in mano ai Turchi Ottomani, ponendo fine all\'Impero Romano d\'Oriente?',o:['1453','1204','1291','1389'],a:'1453'},
  {s:'Medioevo',t:'Basso Medioevo',b:'remember',c:'La Guerra dei Cent\'Anni fu combattuta tra quali due paesi?',o:['Francia e Inghilterra','Sacro Romano Impero e Francia','Spagna e Portogallo','Italia e Turchia'],a:'Francia e Inghilterra'},
  {s:'Medioevo',t:'Basso Medioevo',b:'understand',c:'Perché la Peste nera ebbe conseguenze sociali così profonde oltre all\'enorme mortalità?',o:['Sconvolse le certezze religiose (perché Dio permetteva ciò?), indebolì il potere della Chiesa e accelerò cambiamenti sociali ed economici (salari più alti, mobilità dei sopravvissuti)','Causò solo morti senza alterare le strutture sociali preesistenti','Rafforzò la fiducia della popolazione nella Chiesa come unica speranza','Non ebbe conseguenze economiche significative perché la popolazione si riprese rapidamente'],a:'Sconvolse le certezze religiose (perché Dio permetteva ciò?), indebolì il potere della Chiesa e accelerò cambiamenti sociali ed economici (salari più alti, mobilità dei sopravvissuti)'},
  {s:'Medioevo',t:'Basso Medioevo',b:'understand',c:'Come si spiega la nascita delle università nel Basso Medioevo (XI-XIII sec.)?',o:['La ripresa economica e urbana creò domanda di personale istruito: giuristi, medici, teologi e funzionari amministrativi','Fu un\'iniziativa del Papa per formare più sacerdoti','I re fondarono le università per addestrare i loro eserciti','Le università nacquero come scuole di artigianato per le corporazioni'],a:'La ripresa economica e urbana creò domanda di personale istruito: giuristi, medici, teologi e funzionari amministrativi'},
  {s:'Medioevo',t:'Basso Medioevo',b:'apply',c:'Un mercante fiorentino del XIV sec. vuole proteggere i suoi capitali dalla crisi economica post-Peste. Quale strategia finanziaria adotta?',o:['Diversifica gli investimenti tra commercio, prestiti e proprietà immobiliari, e usa strumenti finanziari come le lettere di credito','Converte tutto il denaro in oro e lo nasconde in casa','Affida i suoi beni alla gestione della Chiesa','Investe tutto in una sola attività commerciale per massimizzare i profitti'],a:'Diversifica gli investimenti tra commercio, prestiti e proprietà immobiliari, e usa strumenti finanziari come le lettere di credito'},
  {s:'Medioevo',t:'Basso Medioevo',b:'apply',c:'Un re medievale del XIV sec. vuole rafforzare il suo potere contro i baroni feudali. Quale alleanza tattica gli conviene cercare?',o:['Alleanza con le città borghesi (che cercano protezione reale) e con la Chiesa per limitare il potere dell\'aristocrazia feudale','Alleanza con i baroni più potenti contro quelli più deboli','Dichiarare guerra aperta a tutti i baroni contemporaneamente','Chiedere aiuto militare al Papa'],a:'Alleanza con le città borghesi (che cercano protezione reale) e con la Chiesa per limitare il potere dell\'aristocrazia feudale'},
  {s:'Medioevo',t:'Basso Medioevo',b:'analyze',c:'Quali cause concorrenti spiegano la crisi del XIV secolo in Europa (Peste, guerre, carestie)?',o:['Sistema agricolo al limite della capacità, raffreddamento climatico (piccola età glaciale), sovrappopolazione rispetto alle risorse disponibili e conflitti politici','Solo la Peste nera, causa di tutte le altre crisi','La corruzione della Chiesa come causa spirituale di tutti i mali materiali','Un\'invasione mongola che devastò le campagne europee'],a:'Sistema agricolo al limite della capacità, raffreddamento climatico (piccola età glaciale), sovrappopolazione rispetto alle risorse disponibili e conflitti politici'},
  {s:'Medioevo',t:'Basso Medioevo',b:'analyze',c:'Perché la caduta di Costantinopoli nel 1453 ebbe conseguenze così rilevanti per l\'Europa occidentale?',o:['Bloccò o rese molto più costose le rotte commerciali terrestri verso l\'Asia, incentivando la ricerca di nuove rotte marittime (scoperte geografiche)','Non ebbe quasi nessuna conseguenza per l\'Europa occidentale, lontana geograficamente','Causò la fine immediata del commercio di spezie in Europa','Portò all\'alleanza tra Europa e Turchi contro i Mongoli'],a:'Bloccò o rese molto più costose le rotte commerciali terrestri verso l\'Asia, incentivando la ricerca di nuove rotte marittime (scoperte geografiche)'},
  {s:'Medioevo',t:'Basso Medioevo',b:'evaluate',c:'La Guerra dei Cent\'Anni fu determinante per la formazione delle identità nazionali di Francia e Inghilterra?',o:['Sì: la figura di Giovanna d\'Arco cristallizzò la coscienza nazionale francese, mentre l\'Inghilterra sconfitta si identificò sempre più come nazione insulare separata dal continente','No: le identità nazionali si formarono solo nel XIX secolo, indipendentemente dalla guerra','La guerra creò solo un\'identità inglese, non francese','L\'identità nazionale era già pienamente formata prima della guerra'],a:'Sì: la figura di Giovanna d\'Arco cristallizzò la coscienza nazionale francese, mentre l\'Inghilterra sconfitta si identificò sempre più come nazione insulare separata dal continente'},
  {s:'Medioevo',t:'Basso Medioevo',b:'create',c:'Se la Peste nera non avesse colpito l\'Europa nel 1347-1353, come si sarebbe sviluppata la società medievale nel XIV-XV sec.?',o:['Il feudalesimo sarebbe declinato più lentamente, il Rinascimento sarebbe giunto in ritardo, e la struttura sociale più statica avrebbe rallentato la mobilità sociale e le riforme religiose','Nulla sarebbe cambiato: i processi storici sarebbero stati identici','L\'Europa sarebbe rimasta completamente agricola senza mai sviluppare le città','La popolazione sarebbe cresciuta troppo causando una crisi ancora peggiore'],a:'Il feudalesimo sarebbe declinato più lentamente, il Rinascimento sarebbe giunto in ritardo, e la struttura sociale più statica avrebbe rallentato la mobilità sociale e le riforme religiose'},

  // ── Cultura e religione medievale ─────────────────────────────────
  {s:'Medioevo',t:'Cultura e religione medievale',b:'remember',c:'Quale filosofo medievale è il principale esponente della Scolastica e autore della Summa Theologiae?',o:['Tommaso d\'Aquino','Anselmo d\'Aosta','Pietro Abelardo','Guglielmo di Ockham'],a:'Tommaso d\'Aquino'},
  {s:'Medioevo',t:'Cultura e religione medievale',b:'remember',c:'Chi fondò l\'Ordine dei Frati Minori (Francescani) nel XIII secolo?',o:['Francesco d\'Assisi','Domenico di Guzmán','Bernardo di Chiaravalle','Ignazio di Loyola'],a:'Francesco d\'Assisi'},
  {s:'Medioevo',t:'Cultura e religione medievale',b:'understand',c:'Perché i monasteri medievali furono fondamentali per la conservazione della cultura classica greco-romana?',o:['I monaci copiavano sistematicamente i manoscritti antichi negli scriptoria, preservandoli dalla deteriorazione e dalla distruzione, costituendo vere biblioteche del sapere','I monasteri custodivano solo testi religiosi cristiani, non opere pagane','La conservazione della cultura classica fu opera esclusiva delle università','Solo Bisanzio conservò i testi antichi, non i monasteri occidentali'],a:'I monaci copiavano sistematicamente i manoscritti antichi negli scriptoria, preservandoli dalla deteriorazione e dalla distruzione, costituendo vere biblioteche del sapere'},
  {s:'Medioevo',t:'Cultura e religione medievale',b:'understand',c:'Cosa si intende con "Scolastica" nella filosofia medievale?',o:['Il tentativo sistematico di conciliare la fede cristiana con la ragione aristotelica, usando la logica per dimostrare le verità religiose','Una scuola di pensiero che rifiutava la ragione in favore della pura fede','Un movimento filosofico che poneva la scienza al di sopra della religione','Una corrente artistica caratterizzata da decorazioni nelle scuole cattedrali'],a:'Il tentativo sistematico di conciliare la fede cristiana con la ragione aristotelica, usando la logica per dimostrare le verità religiose'},
  {s:'Medioevo',t:'Cultura e religione medievale',b:'apply',c:'Un teologo medievale viene accusato di eresia. Come si difenderà di fronte al tribunale ecclesiastico?',o:['Citerà le Scritture, i Padri della Chiesa, le opere di Aristotele e le decisioni dei Concili per dimostrare l\'ortodossia delle sue posizioni','Rifiuterà la giurisdizione del tribunale come illegittima','Si appellerà direttamente al re per protezione politica','Ammetterà l\'eresia in cambio di una pena ridotta'],a:'Citerà le Scritture, i Padri della Chiesa, le opere di Aristotele e le decisioni dei Concili per dimostrare l\'ortodossia delle sue posizioni'},
  {s:'Medioevo',t:'Cultura e religione medievale',b:'apply',c:'Un pellegrino medievale si prepara per il Cammino di Santiago de Compostela. Quali preparativi pratici fa?',o:['Si confessa, redige un testamento, si munisce di un documento ecclesiastico di protezione e si equipaggia con bastone, mantello e bisaccia','Arruola una scorta militare privata per proteggersi dai briganti','Acquista una mappa dettagliata del percorso da una bottega cartografica','Prenota in anticipo le soste presso le locande lungo il percorso'],a:'Si confessa, redige un testamento, si munisce di un documento ecclesiastico di protezione e si equipaggia con bastone, mantello e bisaccia'},
  {s:'Medioevo',t:'Cultura e religione medievale',b:'analyze',c:'Quali funzioni sociali e simboliche svolgeva la cattedrale gotica nel contesto della città medievale?',o:['Centro religioso, polo identitario civico, luogo di assemblee, mercato nel sagrato e simbolo visibile della potenza della comunità verso Dio e i forestieri','Solo un luogo di culto senza funzioni sociali o politiche','Un\'istituzione esclusivamente al servizio dell\'élite aristocratica e del clero','Una fortezza militare travestita da edificio religioso'],a:'Centro religioso, polo identitario civico, luogo di assemblee, mercato nel sagrato e simbolo visibile della potenza della comunità verso Dio e i forestieri'},
  {s:'Medioevo',t:'Cultura e religione medievale',b:'analyze',c:'Perché l\'eresia catara (albigese) si diffuse così capillarmente nel Sud della Francia nel XII-XIII sec.?',o:['Critica alla corruzione e alla ricchezza del clero cattolico, messaggio di purezza spirituale, struttura comunitaria alternativa e sostegno di parte dell\'aristocrazia locale','Era imposta con la forza da nobili locali che cercavano l\'indipendenza da Roma','La Chiesa non si accorse della sua diffusione per secoli','I Catari promettevano miracoli economici ai loro seguaci'],a:'Critica alla corruzione e alla ricchezza del clero cattolico, messaggio di purezza spirituale, struttura comunitaria alternativa e sostegno di parte dell\'aristocrazia locale'},
  {s:'Medioevo',t:'Cultura e religione medievale',b:'evaluate',c:'Il Medioevo fu davvero un\'Età Buia come lo definirono gli umanisti rinascimentali?',o:['No: fu un periodo di grande creatività artistica (cattedrali gotiche), filosofica (Scolastica) e istituzionale (università, parlamenti), anche se con limiti reali rispetto all\'antichità classica','Sì: non vi fu alcun progresso in nessun campo del sapere umano','Sì per i secoli V-X, ma dal XI sec. fu pienamente paragonabile all\'antichità','No: fu il periodo più avanzato della storia europea, superiore al Rinascimento'],a:'No: fu un periodo di grande creatività artistica (cattedrali gotiche), filosofica (Scolastica) e istituzionale (università, parlamenti), anche se con limiti reali rispetto all\'antichità classica'},
  {s:'Medioevo',t:'Cultura e religione medievale',b:'create',c:'Se la stampa a caratteri mobili fosse stata inventata nel X sec. invece che nel XV, come si sarebbe sviluppata la cultura medievale?',o:['Diffusione molto più rapida delle idee eretiche e riformatrici, con una possibile Riforma religiosa anticipata di secoli, maggiore alfabetizzazione laica e declino del monopolio culturale ecclesiastico','Nulla sarebbe cambiato: i contenuti erano già disponibili in manoscritto','La Chiesa avrebbe immediatamente distrutto tutte le stamperie','Solo l\'arte sarebbe migliorata grazie alla diffusione dei libri illustrati'],a:'Diffusione molto più rapida delle idee eretiche e riformatrici, con una possibile Riforma religiosa anticipata di secoli, maggiore alfabetizzazione laica e declino del monopolio culturale ecclesiastico'},
];
async function main(){const token=await getToken();let ok=0,fail=0;for(const q of Q){const res=await fetch(`${PB_URL}/api/collections/Question/records`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({subject:q.s,topic:q.t,content:q.c,options:q.o,correct_answer:q.a,bloom_level:q.b,owner:OWNER})});if(res.ok){ok++;process.stdout.write(`\r  ${ok}/${Q.length}`);}else{fail++;console.error('\nFAIL',q.c.slice(0,40),await res.text());}}console.log(`\nMedioevo: ${ok} ok, ${fail} fail`);}
main().catch(console.error);
