const PB_URL = 'http://127.0.0.1:8090';
const OWNER  = 'chmzino5e3lqgca';
async function getToken() {
  const res = await fetch(`${PB_URL}/api/collections/_superusers/auth-with-password`, {
    method:'POST',headers:{'Content-Type':'application/json'},
    body:JSON.stringify({identity:'whatnico007@gmail.com',password:'Pocketbasemerda1'}),
  });
  return (await res.json()).token;
}
const Q = [
  // ── Civiltà mesopotamiche ──────────────────────────────────────────
  {s:'Storia Antica',t:'Civiltà mesopotamiche',b:'remember',c:'Come si chiama la scrittura inventata dai Sumeri in Mesopotamia?',o:['Scrittura cuneiforme','Geroglifici','Alfabeto fenicio','Lineare B'],a:'Scrittura cuneiforme'},
  {s:'Storia Antica',t:'Civiltà mesopotamiche',b:'remember',c:'Come si chiama il più famoso codice di leggi mesopotamico, attribuito al re babilonese del XVIII sec. a.C.?',o:['Codice di Hammurabi','Leggi di Ur-Nammu','Codice di Draco','Leggi delle XII Tavole'],a:'Codice di Hammurabi'},
  {s:'Storia Antica',t:'Civiltà mesopotamiche',b:'understand',c:'Perché le ziggurat erano al centro della vita urbana sumerica?',o:['Concentravano potere religioso, economico e amministrativo in un unico edificio-tempio','Erano solo luoghi di culto senza funzioni pratiche','Servivano come abitazioni per la popolazione durante le inondazioni','Erano strutture difensive contro le invasioni'],a:'Concentravano potere religioso, economico e amministrativo in un unico edificio-tempio'},
  {s:'Storia Antica',t:'Civiltà mesopotamiche',b:'understand',c:'Cosa ci rivela l\'Epopea di Gilgameš sulla visione del mondo mesopotamica?',o:['Una visione pessimistica della mortalità umana e il desiderio insoddisfatto di immortalità','Un ottimismo sulla vita dopo la morte simile a quello egizio','La certezza che gli dei proteggessero sempre i giusti','La credenza nella reincarnazione dell\'anima'],a:'Una visione pessimistica della mortalità umana e il desiderio insoddisfatto di immortalità'},
  {s:'Storia Antica',t:'Civiltà mesopotamiche',b:'apply',c:'Un funzionario babilonese deve giudicare una controversia tra un mercante e un agricoltore per un debito. Quale strumento normativo consulterà?',o:['Il Codice di Hammurabi come riferimento legale scritto','La tradizione orale tramandata dai sacerdoti','Il giudizio personale del re senza riferimenti scritti','Le leggi greche importate dal Mediterraneo'],a:'Il Codice di Hammurabi come riferimento legale scritto'},
  {s:'Storia Antica',t:'Civiltà mesopotamiche',b:'apply',c:'Un contabile sumero deve registrare la distribuzione di razioni di grano ai lavoratori di un tempio. Quale sistema usa?',o:['Scrittura cuneiforme su tavolette di argilla con segni numerici','Pittura su pareti di pietra come in Egitto','Alfabeto fonetico su papiro','Nodi su corda come nelle civiltà andine'],a:'Scrittura cuneiforme su tavolette di argilla con segni numerici'},
  {s:'Storia Antica',t:'Civiltà mesopotamiche',b:'analyze',c:'Quali fattori geografici favorirono la nascita delle prime città-stato in Mesopotamia?',o:['La fertilità della pianura alluvionale tra Tigri ed Eufrate, l\'irrigazione possibile e la posizione di crocevia commerciale','La presenza di montagne che proteggevano dai nemici','L\'abbondanza di pietra per costruire grandi edifici','Il clima freddo che obbligava a costruire abitazioni robuste'],a:'La fertilità della pianura alluvionale tra Tigri ed Eufrate, l\'irrigazione possibile e la posizione di crocevia commerciale'},
  {s:'Storia Antica',t:'Civiltà mesopotamiche',b:'analyze',c:'Confrontando l\'Impero Assiro e quello Neo-Babilonese, quali differenze strutturali emergono?',o:['L\'Assiro fondato su terrore militare e deportazioni; il Neo-Babilonese più orientato al commercio e alla cultura','Erano praticamente identici nella struttura politica e militare','L\'Assiro era più pacifico; il Babilonese più aggressivo militarmente','L\'Assiro era monoteista; il Babilonese politeista'],a:'L\'Assiro fondato su terrore militare e deportazioni; il Neo-Babilonese più orientato al commercio e alla cultura'},
  {s:'Storia Antica',t:'Civiltà mesopotamiche',b:'evaluate',c:'Quale fu la più importante eredità delle civiltà mesopotamiche per la storia dell\'umanità?',o:['L\'invenzione della scrittura cuneiforme e i primi sistemi legali codificati, che influenzarono tutte le civiltà successive','La costruzione delle ziggurat, che ispirarono le piramidi egizie','L\'invenzione della ruota, usata solo in Mesopotamia','Il primo esercito professionale della storia'],a:'L\'invenzione della scrittura cuneiforme e i primi sistemi legali codificati, che influenzarono tutte le civiltà successive'},
  {s:'Storia Antica',t:'Civiltà mesopotamiche',b:'create',c:'Se la scrittura cuneiforme non fosse mai stata inventata, quale sistema alternativo avrebbe potuto sostenere l\'amministrazione delle prime città mesopotamiche?',o:['Sistemi di token fisici tridimensionali già esistenti, con pittogrammi più elaborati e memorizzazione orale ritualizzata','Un sistema alfabetico sviluppato in modo indipendente e precoce','La comunicazione esclusivamente orale attraverso messaggeri specializzati','L\'uso di nodi e corde come sistema contabile alternativo'],a:'Sistemi di token fisici tridimensionali già esistenti, con pittogrammi più elaborati e memorizzazione orale ritualizzata'},

  // ── Egitto antico ──────────────────────────────────────────────────
  {s:'Storia Antica',t:'Egitto antico',b:'remember',c:'Quale faraone è tradizionalmente associato alla costruzione della Grande Piramide di Giza?',o:['Cheope (Khufu)','Ramesse II','Tutankhamon','Akhenaton'],a:'Cheope (Khufu)'},
  {s:'Storia Antica',t:'Egitto antico',b:'remember',c:'Quale stele permise di decifrare i geroglifici egizi nel XIX secolo?',o:['La Stele di Rosetta','La Pietra di Palermo','L\'Obelisco di Luxor','La Tavola di Abido'],a:'La Stele di Rosetta'},
  {s:'Storia Antica',t:'Egitto antico',b:'understand',c:'Perché il Nilo era fondamentale per la sopravvivenza della civiltà egizia?',o:['Le sue piene annuali depositavano limo fertile, rendendo possibile l\'agricoltura nel deserto','Era l\'unica fonte d\'acqua potabile in tutto il continente africano','Proteggeva l\'Egitto dagli invasori con le sue rapide invalicabili','Permetteva la pesca intensiva come unica fonte alimentare'],a:'Le sue piene annuali depositavano limo fertile, rendendo possibile l\'agricoltura nel deserto'},
  {s:'Storia Antica',t:'Egitto antico',b:'understand',c:'Cosa ci indica la pratica della mummificazione riguardo alle credenze religiose egizie?',o:['La credenza in una vita ultraterrena corporea che richiedeva la conservazione del corpo fisico','Una preoccupazione igienica per prevenire malattie nei climi caldi','Una pratica medica per studiare l\'anatomia umana','Un rito funebre puramente simbolico senza credenze sull\'aldilà'],a:'La credenza in una vita ultraterrena corporea che richiedeva la conservazione del corpo fisico'},
  {s:'Storia Antica',t:'Egitto antico',b:'apply',c:'Un faraone vuole rafforzare la propria legittimità divina dopo una sconfitta militare imbarazzante. Quale strumento propagandistico utilizzerà?',o:['Commissionare templi e iscrizioni che glorifichino una sua "vittoria" (come Ramesse II fece con la battaglia di Qadesh)','Abdicare in favore di un successore più capace','Consultare pubblicamente il popolo attraverso assemblee','Riconoscere la sconfitta e pagare il tributo ai vincitori'],a:'Commissionare templi e iscrizioni che glorifichino una sua "vittoria" (come Ramesse II fece con la battaglia di Qadesh)'},
  {s:'Storia Antica',t:'Egitto antico',b:'apply',c:'Un egittologo trova una tomba con vasi canopi, shabtis e iscrizioni del Libro dei Morti. Quale conclusione trae?',o:['Tomba di un alto funzionario con equipaggiamento completo per il viaggio nell\'aldilà','Laboratorio di alchimia medievale riadattato da una struttura antica','Deposito alimentare di un palazzo reale','Tomba di un sacerdote che non credeva nell\'aldilà'],a:'Tomba di un alto funzionario con equipaggiamento completo per il viaggio nell\'aldilà'},
  {s:'Storia Antica',t:'Egitto antico',b:'analyze',c:'Quali fattori spiegano la straordinaria stabilità della civiltà egizia per oltre 3000 anni?',o:['Isolamento geografico del deserto, regime del Nilo prevedibile e forte ideologia religiosa faraonica che legittimava l\'ordine sociale','L\'assenza di nemici esterni in tutta la storia egiziana','Un sistema democratico che garantiva stabilità politica','La tecnologia superiore che scoraggiava qualsiasi invasione'],a:'Isolamento geografico del deserto, regime del Nilo prevedibile e forte ideologia religiosa faraonica che legittimava l\'ordine sociale'},
  {s:'Storia Antica',t:'Egitto antico',b:'analyze',c:'Perché la riforma religiosa di Akhenaton (culto monoteistico di Aton) fallì e fu cancellata dai successori?',o:['Minacciava il potere economico del potente clero di Amon e rompeva millenni di tradizione religiosa politeista','Il popolo non capì il nuovo concetto di dio unico','La riforma era troppo costosa per le finanze dello stato','Akhenaton morì troppo giovane prima di poterla consolidare'],a:'Minacciava il potere economico del potente clero di Amon e rompeva millenni di tradizione religiosa politeista'},
  {s:'Storia Antica',t:'Egitto antico',b:'evaluate',c:'Quale periodo della storia egizia produsse le realizzazioni architettoniche e artistiche più significative?',o:['Sia l\'Antico Regno (piramidi di Giza) che il Nuovo Regno (templi di Karnak e Abu Simbel), per ragioni e contesti diversi','Solo il Nuovo Regno: l\'Antico Regno produsse solo strutture funzionali','Solo l\'Antico Regno: il Nuovo Regno fu un periodo di decadenza','Il Periodo Tardo, quando l\'Egitto era già sotto influenza persiana'],a:'Sia l\'Antico Regno (piramidi di Giza) che il Nuovo Regno (templi di Karnak e Abu Simbel), per ragioni e contesti diversi'},
  {s:'Storia Antica',t:'Egitto antico',b:'create',c:'Se Alessandro Magno non avesse conquistato l\'Egitto nel 332 a.C., come si sarebbe probabilmente evoluta la civiltà egizia?',o:['Sarebbe rimasta sotto influenza persiana o avrebbe recuperato autonomia, mantenendo più a lungo la cultura tradizionale senza ellenizzazione','Si sarebbe estinta spontaneamente a causa della crisi interna','Si sarebbe trasformata in una democrazia sulla base del modello ateniese','Avrebbe conquistato a sua volta la Persia e fondato un proprio impero'],a:'Sarebbe rimasta sotto influenza persiana o avrebbe recuperato autonomia, mantenendo più a lungo la cultura tradizionale senza ellenizzazione'},

  // ── Grecia antica ─────────────────────────────────────────────────
  {s:'Storia Antica',t:'Grecia antica',b:'remember',c:'In quale anno avvenne la battaglia di Maratona?',o:['490 a.C.','480 a.C.','334 a.C.','431 a.C.'],a:'490 a.C.'},
  {s:'Storia Antica',t:'Grecia antica',b:'remember',c:'Chi fu il principale filosofo ateniese condannato a morte per empietà e corruzione della gioventù nel 399 a.C.?',o:['Socrate','Platone','Aristotele','Anassagora'],a:'Socrate'},
  {s:'Storia Antica',t:'Grecia antica',b:'understand',c:'Perché la polis greca è considerata una forma politica originale e innovativa nel mondo antico?',o:['Concentrava l\'autogoverno in una comunità di cittadini con partecipazione diretta alle decisioni, senza un re-dio','Era il primo stato con un esercito professionale stipendiato','Garantiva diritti uguali a tutti gli abitanti, inclusi schiavi e donne','Era governata da sacerdoti eletti democraticamente'],a:'Concentrava l\'autogoverno in una comunità di cittadini con partecipazione diretta alle decisioni, senza un re-dio'},
  {s:'Storia Antica',t:'Grecia antica',b:'understand',c:'Come si differenzia fondamentalmente il sistema politico di Atene da quello di Sparta nel V sec. a.C.?',o:['Atene aveva una democrazia diretta con assemblea dei cittadini; Sparta una diarchia militare con due re e un Consiglio degli anziani (Gerousia)','Atene era governata da un re; Sparta da un\'assemblea popolare','Non c\'era alcuna differenza politica sostanziale tra le due poleis','Atene era una tirannia; Sparta una democrazia'],a:'Atene aveva una democrazia diretta con assemblea dei cittadini; Sparta una diarchia militare con due re e un Consiglio degli anziani (Gerousia)'},
  {s:'Storia Antica',t:'Grecia antica',b:'apply',c:'Un cittadino ateniese del V sec. a.C. vuole proporre una nuova legge sulla gestione delle finanze pubbliche. Quale procedura seguirà?',o:['Presenterà la proposta all\'Ecclesia (assemblea di tutti i cittadini maschi adulti) dove sarà discussa e votata','La presenterà al re che deciderà autonomamente','La sottoporrà al voto del Senato composto da aristocratici','La proposta sarà valutata da un collegio di sacerdoti'],a:'Presenterà la proposta all\'Ecclesia (assemblea di tutti i cittadini maschi adulti) dove sarà discussa e votata'},
  {s:'Storia Antica',t:'Grecia antica',b:'apply',c:'Un generale greco deve scegliere tra affrontare l\'esercito persiano in campo aperto o difendere un passo montano stretto. Quale ragione strategica lo spinge a scegliere il passo?',o:['Il terreno stretto neutralizza la superiorità numerica persiana, rendendo efficace anche un esercito più piccolo (come alle Termopili)','Il campo aperto è sempre preferibile perché permette la manovra','Il passo è più facile da approvvigionare logisticamente','I soldati greci erano più efficaci nella difesa che nell\'attacco'],a:'Il terreno stretto neutralizza la superiorità numerica persiana, rendendo efficace anche un esercito più piccolo (come alle Termopili)'},
  {s:'Storia Antica',t:'Grecia antica',b:'analyze',c:'Quali cause strutturali portarono alla guerra del Peloponneso tra Atene e Sparta (431–404 a.C.)?',o:['La crescita del potere imperiale ateniese e della Lega delio-attica spaventò Sparta e i suoi alleati del Peloponneso','Una disputa religiosa sul controllo del santuario di Delfi','L\'assassinio dell\'ambasciatore spartano ad Atene','La rivalità personale tra Pericle e il re spartano Archidamo'],a:'La crescita del potere imperiale ateniese e della Lega delio-attica spaventò Sparta e i suoi alleati del Peloponneso'},
  {s:'Storia Antica',t:'Grecia antica',b:'analyze',c:'Perché la democrazia ateniese del V sec. a.C. non era una democrazia nel senso moderno del termine?',o:['Escludeva donne, schiavi e stranieri residenti (meteci) dalla partecipazione politica, lasciando il voto solo ai maschi adulti cittadini','Era identica alla democrazia moderna, con suffragio universale','Era meno democratica dell\'odierna solo per l\'assenza di partiti politici organizzati','Ammetteva tutti gli abitanti tranne i bambini'],a:'Escludeva donne, schiavi e stranieri residenti (meteci) dalla partecipazione politica, lasciando il voto solo ai maschi adulti cittadini'},
  {s:'Storia Antica',t:'Grecia antica',b:'evaluate',c:'Quale fu la conseguenza più duratura della civiltà greca per la cultura occidentale?',o:['La filosofia, il teatro, la scienza naturale e il concetto di democrazia come fondamento del pensiero e delle istituzioni europee','L\'invenzione dell\'alfabeto, che permise la scrittura moderna','La costruzione del Partenone, modello di tutta l\'architettura occidentale','La creazione del primo esercito professionale permanente'],a:'La filosofia, il teatro, la scienza naturale e il concetto di democrazia come fondamento del pensiero e delle istituzioni europee'},
  {s:'Storia Antica',t:'Grecia antica',b:'create',c:'Se Alessandro Magno non fosse morto improvvisamente a 32 anni nel 323 a.C., come avrebbe potuto cambiare la storia del mondo antico?',o:['Possibile consolidamento di un vasto impero stabile con ulteriore ellenizzazione dell\'Asia e forse nuove conquiste verso India e Arabia','L\'impero si sarebbe automaticamente dissolto per le sue dimensioni eccessive','Roma avrebbe comunque dominato il Mediterraneo nello stesso periodo','La Cina avrebbe fermato l\'espansione verso oriente'],a:'Possibile consolidamento di un vasto impero stabile con ulteriore ellenizzazione dell\'Asia e forse nuove conquiste verso India e Arabia'},

  // ── Roma antica ───────────────────────────────────────────────────
  {s:'Storia Antica',t:'Roma antica',b:'remember',c:'In quale anno fu assassinato Giulio Cesare?',o:['44 a.C.','27 a.C.','100 a.C.','14 d.C.'],a:'44 a.C.'},
  {s:'Storia Antica',t:'Roma antica',b:'remember',c:'In quale anno cade convenzionalmente l\'Impero Romano d\'Occidente?',o:['476 d.C.','410 d.C.','395 d.C.','565 d.C.'],a:'476 d.C.'},
  {s:'Storia Antica',t:'Roma antica',b:'understand',c:'Perché la crisi delle istituzioni repubblicane romane nel I sec. a.C. portò all\'istituzione del Principato?',o:['Le guerre civili e l\'instabilità istituzionale rendevano necessario un potere più centralizzato; Augusto mantenne le forme repubblicane con il potere sostanziale nelle sue mani','La Repubblica fu abolita con un voto popolare democratico','Il Senato scelse di delegare tutto il potere a un imperatore eletto a vita','Una rivolta popolare rovesciò il Senato e impose il governo di un uomo solo'],a:'Le guerre civili e l\'instabilità istituzionale rendevano necessario un potere più centralizzato; Augusto mantenne le forme repubblicane con il potere sostanziale nelle sue mani'},
  {s:'Storia Antica',t:'Roma antica',b:'understand',c:'Come funzionava il sistema della clientela nella società romana?',o:['Un cittadino potente (patronus) proteggeva i clienti in cambio di supporto politico, voti e servizi quotidiani','Era un sistema bancario per prestare denaro ai poveri','I clienti erano servi con obblighi di lavoro fisico','Era una forma di commercio basata sul baratto'],a:'Un cittadino potente (patronus) proteggeva i clienti in cambio di supporto politico, voti e servizi quotidiani'},
  {s:'Storia Antica',t:'Roma antica',b:'apply',c:'Un senatore romano del I sec. a.C. vuole bloccare una proposta di legge di Giulio Cesare nell\'assemblea. Quale strumento istituzionale può usare?',o:['Il veto tribunizio (se tribuno della plebe) o un discorso ostruzionistico infinito per far scadere il tempo utile','Ordinare l\'arresto di Cesare con l\'autorità senatoriale','Indire un referendum popolare per annullare la proposta','Appellarsi direttamente al re'],a:'Il veto tribunizio (se tribuno della plebe) o un discorso ostruzionistico infinito per far scadere il tempo utile'},
  {s:'Storia Antica',t:'Roma antica',b:'apply',c:'Un generale romano viene inviato a governare una provincia appena conquistata. Quali misure adotterà per stabilizzarla?',o:['Costruire strade e infrastrutture, insediare coloni, rispettare le élite locali e riscuotere tributi in modo regolare','Distruggere tutte le strutture locali preesistenti e imporre la cultura romana per forza','Lasciare completa autonomia alla popolazione locale senza alcuna supervisione','Deportare l\'intera popolazione in Italia e ripopolare con romani'],a:'Costruire strade e infrastrutture, insediare coloni, rispettare le élite locali e riscuotere tributi in modo regolare'},
  {s:'Storia Antica',t:'Roma antica',b:'analyze',c:'Quali fattori interni ed esterni contribuirono alla caduta dell\'Impero Romano d\'Occidente nel 476 d.C.?',o:['Pressioni barbariche esterne, crisi economica e monetaria, instabilità politica con imperatori-soldato, eccessi di spesa militare e divisione dell\'impero','Solo le invasioni barbariche, senza crisi interne significative','Esclusivamente la diffusione del Cristianesimo che indebolì lo spirito guerriero','Il cambiamento climatico che rese impossibile l\'agricoltura mediterranea'],a:'Pressioni barbariche esterne, crisi economica e monetaria, instabilità politica con imperatori-soldato, eccessi di spesa militare e divisione dell\'impero'},
  {s:'Storia Antica',t:'Roma antica',b:'analyze',c:'Confrontando la Repubblica e l\'Impero romano, quali differenze strutturali emergono nel governo?',o:['La Repubblica aveva magistrati annuali con controllo senatoriale e bilanciamento dei poteri; l\'Impero concentrava il potere nell\'imperatore, anche se mantenendo formalmente le istituzioni repubblicane','Nell\'Impero il Senato aveva più potere che nella Repubblica','Non c\'era alcuna differenza strutturale sostanziale','La Repubblica era più centralizzata; l\'Impero più federalista'],a:'La Repubblica aveva magistrati annuali con controllo senatoriale e bilanciamento dei poteri; l\'Impero concentrava il potere nell\'imperatore, anche se mantenendo formalmente le istituzioni repubblicane'},
  {s:'Storia Antica',t:'Roma antica',b:'evaluate',c:'Quale fu la più duratura eredità di Roma per la civiltà europea?',o:['Il diritto romano come fondamento dei sistemi giuridici moderni, la lingua latina come madre delle lingue romanze e l\'organizzazione amministrativa territoriale','La tecnologia militare, superiore a qualsiasi altra nella storia','L\'architettura monumentale, copiata da tutti i popoli europei','La religione pagana romana, che sopravvisse fino al XX secolo'],a:'Il diritto romano come fondamento dei sistemi giuridici moderni, la lingua latina come madre delle lingue romanze e l\'organizzazione amministrativa territoriale'},
  {s:'Storia Antica',t:'Roma antica',b:'create',c:'Se Roma non avesse adottato il Cristianesimo come religione di stato nel IV sec. d.C., quale sarebbe stato il probabile sviluppo religioso dell\'Europa?',o:['Sopravvivenza più lunga del politeismo romano-greco o affermazione di un\'altra religione monoteista come il Mithraismo o il Manicheismo','Il Buddhismo si sarebbe diffuso dall\'Asia in Europa','L\'Islam avrebbe conquistato l\'Europa prima del VII sec.','Il politeismo germanico avrebbe dominato tutta l\'Europa'],a:'Sopravvivenza più lunga del politeismo romano-greco o affermazione di un\'altra religione monoteista come il Mithraismo o il Manicheismo'},

  // ── Civiltà orientali ─────────────────────────────────────────────
  {s:'Storia Antica',t:'Civiltà orientali',b:'remember',c:'Chi fu il primo imperatore della Cina unificata (221 a.C.)?',o:['Qin Shi Huang','Han Wudi','Confucio','Sun Tzu'],a:'Qin Shi Huang'},
  {s:'Storia Antica',t:'Civiltà orientali',b:'remember',c:'Quale rotta commerciale collegava la Cina con il Mediterraneo nell\'antichità?',o:['La Via della Seta','La Rotta delle Spezie','Il Corridoio del Nord','La Via dell\'Ambra'],a:'La Via della Seta'},
  {s:'Storia Antica',t:'Civiltà orientali',b:'understand',c:'Perché l\'insegnamento di Confucio ebbe un\'influenza così duratura sulla società cinese per più di 2000 anni?',o:['Fornì un codice etico e gerarchico (pietà filiale, rispetto dell\'autorità) che giustificava l\'ordine sociale e rendeva legittimo il potere dello stato','Era imposto con la forza da ogni dinastia cinese senza alternativa','Offriva promesse di vita eterna simili alle religioni monoteiste','Era l\'unica filosofia disponibile in Cina fino all\'arrivo del Buddhismo'],a:'Fornì un codice etico e gerarchico (pietà filiale, rispetto dell\'autorità) che giustificava l\'ordine sociale e rendeva legittimo il potere dello stato'},
  {s:'Storia Antica',t:'Civiltà orientali',b:'understand',c:'Cosa distingueva la visione politica dell\'imperatore Ashoka (India, III sec. a.C.) dalla tipica concezione imperiale antica?',o:['Ashoka rinunciò alla conquista militare dopo la sanguinosa battaglia di Kalinga e governò secondo principi buddisti di compassione e non-violenza','Ashoka fu il primo imperatore a istituire la democrazia in Asia','Ashoka concentrò il potere religioso e politico in un\'unica figura sacerdotale','Ashoka espanse l\'impero con la diplomazia invece che con la guerra in tutta la sua storia'],a:'Ashoka rinunciò alla conquista militare dopo la sanguinosa battaglia di Kalinga e governò secondo principi buddisti di compassione e non-violenza'},
  {s:'Storia Antica',t:'Civiltà orientali',b:'apply',c:'Un imperatore cinese ha appena rovesciato la dinastia precedente e ha bisogno di legittimare il suo potere. Quale concetto confuciano utilizzerà?',o:['Il "Mandato del Cielo": il cielo ha ritirato il favore alla vecchia dinastia e lo ha concesso alla nuova','Il diritto di conquista militare come unica legittimazione','La discendenza divina da un dio solare','L\'approvazione del popolo attraverso un\'assemblea'],a:'Il "Mandato del Cielo": il cielo ha ritirato il favore alla vecchia dinastia e lo ha concesso alla nuova'},
  {s:'Storia Antica',t:'Civiltà orientali',b:'apply',c:'Un mercante persiano del V sec. a.C. deve negoziare un accordo con funzionari di province diverse dell\'Impero Achemenide. Quale lingua userà come lingua franca amministrativa?',o:['L\'aramaico, lingua amministrativa dell\'Impero Achemenide','Il persiano antico, incomprensibile nelle province orientali','Il greco, già lingua internazionale nel V sec. a.C.','Il sanscrito, usato in tutto il Medio Oriente'],a:'L\'aramaico, lingua amministrativa dell\'Impero Achemenide'},
  {s:'Storia Antica',t:'Civiltà orientali',b:'analyze',c:'Perché l\'Impero Achemenide persiano riuscì a governare territori vastissimi con popolazioni e culture molto diverse?',o:['Tolleranza religiosa verso le culture locali, sistema di satrapie con deleghe ai governatori, rete stradale efficiente (strada reale) e moneta unificata','Un esercito così grande da rendere impossibile qualsiasi rivolta','L\'imposizione della cultura persiana come unica ammessa in tutto l\'impero','Un sistema di comunicazione telegrafico ante-litteram'],a:'Tolleranza religiosa verso le culture locali, sistema di satrapie con deleghe ai governatori, rete stradale efficiente (strada reale) e moneta unificata'},
  {s:'Storia Antica',t:'Civiltà orientali',b:'analyze',c:'Quali elementi comuni si ritrovano nelle prime civiltà fluviali (Mesopotamia, Egitto, Indo, Cina)?',o:['Tutte sorsero vicino a grandi fiumi, svilupparono scrittura, agricoltura irrigua e strutture statali con élite sacerdotali o burocratiche','Tutte svilupparono il commercio marittimo come principale fonte di ricchezza','Tutte adottarono il monoteismo come religione ufficiale','Tutte costruirono grandi piramidi come simbolo del potere'],a:'Tutte sorsero vicino a grandi fiumi, svilupparono scrittura, agricoltura irrigua e strutture statali con élite sacerdotali o burocratiche'},
  {s:'Storia Antica',t:'Civiltà orientali',b:'evaluate',c:'Quale civiltà orientale antica ebbe il contributo più significativo allo sviluppo della matematica e dell\'astronomia?',o:['La Mesopotamia babilonese, con il sistema sessagesimale (base 60), le tavole matematiche e le osservazioni astronomiche sistematiche','La Cina Han, con l\'invenzione della carta e della stampa','L\'India Maurya, con il sistema dei numeri decimali','La Persia Achemenide, con il calendario solare più preciso'],a:'La Mesopotamia babilonese, con il sistema sessagesimale (base 60), le tavole matematiche e le osservazioni astronomiche sistematiche'},
  {s:'Storia Antica',t:'Civiltà orientali',b:'create',c:'Se la Via della Seta non fosse mai esistita, come sarebbe cambiato lo sviluppo culturale ed economico dell\'Eurasia?',o:['Minore diffusione di tecnologie (carta, bussola), religioni (Buddhismo, Islam) e merci di lusso; sviluppo più compartimentato e isolato delle civiltà eurasiatiche','Nessun cambiamento: le culture si sarebbero sviluppate esattamente allo stesso modo','Le civiltà europee avrebbero scoperto l\'America prima del XV sec. come alternativa','La Cina avrebbe dominato militarmente tutta l\'Eurasia senza opposizione'],a:'Minore diffusione di tecnologie (carta, bussola), religioni (Buddhismo, Islam) e merci di lusso; sviluppo più compartimentato e isolato delle civiltà eurasiatiche'},
];
async function main() {
  const token = await getToken();
  let ok=0,fail=0;
  for (const q of Q) {
    const res = await fetch(`${PB_URL}/api/collections/Question/records`, {
      method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},
      body:JSON.stringify({subject:q.s,topic:q.t,content:q.c,options:q.o,correct_answer:q.a,bloom_level:q.b,owner:OWNER}),
    });
    if (res.ok){ok++;process.stdout.write(`\r  ${ok}/${Q.length}`);}
    else{fail++;console.error('\nFAIL',q.c.slice(0,40),await res.text());}
  }
  console.log(`\nStoria Antica: ${ok} ok, ${fail} fail`);
}
main().catch(console.error);
