// PREISTORIA — 5 argomenti × 10 domande (2R,2U,2Ap,2An,1Ev,1Cr)
const PB_URL = 'http://127.0.0.1:8090';
const OWNER  = 'chmzino5e3lqgca';

async function getToken() {
  const res = await fetch(`${PB_URL}/api/collections/_superusers/auth-with-password`, {
    method:'POST', headers:{'Content-Type':'application/json'},
    body: JSON.stringify({identity:'whatnico007@gmail.com',password:'Pocketbasemerda1'}),
  });
  return (await res.json()).token;
}

const Q = [
  // ── Origini dell'uomo ──────────────────────────────────────────────
  {s:'Preistoria',t:"Origini dell'uomo",b:'remember',
   c:'Quale specie ominide è considerata la più antica ad essere bipede?',
   o:['Australopithecus afarensis','Homo habilis','Homo erectus','Paranthropus robustus'],a:'Australopithecus afarensis'},
  {s:'Preistoria',t:"Origini dell'uomo",b:'remember',
   c:'In quale continente sono stati rinvenuti i fossili dei più antichi ominidi?',
   o:['Africa','Asia','Europa','America del Sud'],a:'Africa'},
  {s:'Preistoria',t:"Origini dell'uomo",b:'understand',
   c:'Perché il bipedismo è considerato un vantaggio evolutivo fondamentale per gli ominidi?',
   o:['Liberava le mani per usare strumenti e trasportare cibo','Rendeva gli ominidi più veloci dei predatori','Migliorava la capacità di nuoto','Riduceva il consumo energetico rispetto al quadrupedismo'],a:'Liberava le mani per usare strumenti e trasportare cibo'},
  {s:'Preistoria',t:"Origini dell'uomo",b:'understand',
   c:'Cosa ci indica la presenza di strumenti di pietra scheggiata associati all\'Homo habilis?',
   o:['Una capacità cognitiva superiore agli australopitechi, con pianificazione intenzionale','La pratica precoce dell\'agricoltura','L\'uso sistematico del fuoco','La costruzione di abitazioni permanenti'],a:'Una capacità cognitiva superiore agli australopitechi, con pianificazione intenzionale'},
  {s:'Preistoria',t:"Origini dell'uomo",b:'apply',
   c:'Un paleontologo trova un fossile con capacità cranica di 650 cc, postura eretta e tracce di utensili litici. A quale specie lo assocerà più probabilmente?',
   o:['Homo habilis','Australopithecus afarensis','Homo sapiens moderno','Paranthropus boisei'],a:'Homo habilis'},
  {s:'Preistoria',t:"Origini dell'uomo",b:'apply',
   c:'Applicando la teoria Out of Africa, come si spiega la presenza di Homo sapiens in Australia circa 65.000 anni fa?',
   o:['Migrazioni progressive dall\'Africa attraverso l\'Asia meridionale','Evoluzione parallela e indipendente in Australia','Trasporto navale organizzato da popolazioni asiatiche','Deriva genetica casuale senza migrazione'],a:'Migrazioni progressive dall\'Africa attraverso l\'Asia meridionale'},
  {s:'Preistoria',t:"Origini dell'uomo",b:'analyze',
   c:'Quali fattori ambientali favorirono l\'evoluzione del bipedismo nella savana africana?',
   o:['La riduzione delle foreste richiedeva di vedere i predatori e camminare su lunghe distanze','Le foreste dense impedivano la locomozione a quattro zampe','L\'abbondanza di acqua favoriva la postura eretta','La scarsità di cibo nella savana selezionava individui più alti'],a:'La riduzione delle foreste richiedeva di vedere i predatori e camminare su lunghe distanze'},
  {s:'Preistoria',t:"Origini dell'uomo",b:'analyze',
   c:'Confrontando il DNA di Homo sapiens moderno e Homo neanderthalensis, cosa deducono i genetisti?',
   o:['Vi fu un\'ibridazione parziale: i non-africani moderni portano circa il 2% di DNA neanderthaliano','Le due specie erano geneticamente identiche','Nessun contatto genetico avvenne mai tra le due specie','I Neanderthal erano antenati diretti di tutti gli europei moderni'],a:'Vi fu un\'ibridazione parziale: i non-africani moderni portano circa il 2% di DNA neanderthaliano'},
  {s:'Preistoria',t:"Origini dell'uomo",b:'evaluate',
   c:'Tra le ipotesi sull\'estinzione dei Neanderthal, quale è oggi ritenuta più fondata dalla comunità scientifica?',
   o:['Una combinazione di competizione con Homo sapiens, pressione climatica e forse ibridazione','Lo sterminio diretto e deliberato da parte di Homo sapiens','Un\'epidemia di malattia portata da Homo sapiens','Il solo cambiamento climatico, senza alcun ruolo di Homo sapiens'],a:'Una combinazione di competizione con Homo sapiens, pressione climatica e forse ibridazione'},
  {s:'Preistoria',t:"Origini dell'uomo",b:'create',
   c:'Se gli ominidi non avessero mai sviluppato il bipedismo, quale percorso evolutivo alternativo sarebbe stato più plausibile?',
   o:['Maggiore specializzazione arboricola con mani prensili sempre più sviluppate, senza liberazione delle mani per gli utensili','Sviluppo di una corteccia cerebrale ancora più grande rimanendo quadrupedi','Evoluzione verso un\'andatura acquatica anfibia','Estinzione precoce a causa dei predatori della savana'],a:'Maggiore specializzazione arboricola con mani prensili sempre più sviluppate, senza liberazione delle mani per gli utensili'},

  // ── Paleolitico ────────────────────────────────────────────────────
  {s:'Preistoria',t:'Paleolitico',b:'remember',
   c:'Quale tipo di strumenti caratterizzò principalmente il Paleolitico?',
   o:['Pietra scheggiata','Bronzo fuso','Ferro battuto','Ceramica cotta'],a:'Pietra scheggiata'},
  {s:'Preistoria',t:'Paleolitico',b:'remember',
   c:'In quale paese si trovano le famose pitture rupestri di Lascaux?',
   o:['Francia','Spagna','Italia','Germania'],a:'Francia'},
  {s:'Preistoria',t:'Paleolitico',b:'understand',
   c:'Perché gli esseri umani del Paleolitico erano nomadi e non sedentari?',
   o:['Seguivano le migrazioni degli animali e la disponibilità stagionale di cibo','Non conoscevano la tecnica della costruzione','Preferivano vivere all\'aperto per motivi religiosi','Temevano i predatori delle foreste'],a:'Seguivano le migrazioni degli animali e la disponibilità stagionale di cibo'},
  {s:'Preistoria',t:'Paleolitico',b:'understand',
   c:'Cosa ci indicano le Veneri paleolitiche riguardo alla società del tempo?',
   o:['Un probabile culto della fertilità femminile e dell\'abbondanza','Una società matriarcale con regine guerriere','Una pratica artistica puramente estetica senza significato simbolico','L\'inizio della schiavitù femminile'],a:'Un probabile culto della fertilità femminile e dell\'abbondanza'},
  {s:'Preistoria',t:'Paleolitico',b:'apply',
   c:'Un gruppo paleolitico si trova in una zona dove la megafauna è scomparsa. Quale adattamento strategico adotterà più probabilmente?',
   o:['Diversificare la dieta verso prede più piccole, pesci e raccolta intensiva di vegetali','Abbandonare immediatamente la zona senza cercare alternative','Iniziare a coltivare cereali come soluzione immediata','Allevare gli animali rimasti'],a:'Diversificare la dieta verso prede più piccole, pesci e raccolta intensiva di vegetali'},
  {s:'Preistoria',t:'Paleolitico',b:'apply',
   c:'Un archeologo trova un sito con ossa combuste, selci scheggiate e carbone. Quale conclusione trae?',
   o:['Un accampamento con caccia, uso del fuoco per cucinare e lavorazione della pietra','Una sepoltura rituale con offerte votive','Un campo di battaglia con tracce di violenza','Un laboratorio preistorico per la produzione di ceramica'],a:'Un accampamento con caccia, uso del fuoco per cucinare e lavorazione della pietra'},
  {s:'Preistoria',t:'Paleolitico',b:'analyze',
   c:'Quali funzioni avevano probabilmente le pitture nelle grotte paleolitiche?',
   o:['Funzioni rituali legate alla caccia, comunicazione simbolica e affermazione dell\'identità del gruppo','Pura decorazione estetica senza valenza simbolica','Mappe geografiche per orientarsi nel territorio','Registrazioni storiche di eventi reali'],a:'Funzioni rituali legate alla caccia, comunicazione simbolica e affermazione dell\'identità del gruppo'},
  {s:'Preistoria',t:'Paleolitico',b:'analyze',
   c:'In che modo il controllo del fuoco trasformò la vita quotidiana nel Paleolitico?',
   o:['Migliorò la difesa dai predatori, il riscaldamento, la cottura dei cibi e favorì la socialità serale','Solo il riscaldamento nei climi freddi','Permise la fusione dei metalli','Consentì la coltivazione dei cereali'],a:'Migliorò la difesa dai predatori, il riscaldamento, la cottura dei cibi e favorì la socialità serale'},
  {s:'Preistoria',t:'Paleolitico',b:'evaluate',
   c:'Quale interpretazione dell\'arte rupestre paleolitica è oggi ritenuta più convincente dagli studiosi?',
   o:['Un insieme complesso di funzioni rituali, simboliche e sociali, non riducibile a un solo scopo','Arte decorativa prodotta per noia nei periodi di inattività','Mappe di caccia con funzione pratica esclusivamente','Testi religiosi incomprensibili senza una chiave di lettura'],a:'Un insieme complesso di funzioni rituali, simboliche e sociali, non riducibile a un solo scopo'},
  {s:'Preistoria',t:'Paleolitico',b:'create',
   c:'Se gli umani del Paleolitico non avessero sviluppato la lavorazione della pietra, quale materiale alternativo avrebbero potuto sfruttare con maggiore intensità?',
   o:['Legno, osso e avorio, già usati marginalmente ma che avrebbero richiesto tecniche più elaborate','I metalli, già teoricamente disponibili in natura','La ceramica, più facile da lavorare della pietra','Le fibre vegetali per costruire reti e trappole'],a:'Legno, osso e avorio, già usati marginalmente ma che avrebbero richiesto tecniche più elaborate'},

  // ── Neolitico ──────────────────────────────────────────────────────
  {s:'Preistoria',t:'Neolitico',b:'remember',
   c:'Quale processo fondamentale caratterizza la "rivoluzione neolitica"?',
   o:['Il passaggio dall\'economia di caccia-raccolta all\'agricoltura e all\'allevamento','L\'invenzione della scrittura cuneiforme','La scoperta e lavorazione dei metalli','La costruzione delle prime città murate'],a:'Il passaggio dall\'economia di caccia-raccolta all\'agricoltura e all\'allevamento'},
  {s:'Preistoria',t:'Neolitico',b:'remember',
   c:'In quale regione del mondo fu coltivato per primo il frumento?',
   o:['Mezzaluna Fertile (Medio Oriente)','Valle del Nilo','Valle dell\'Indo','Cina settentrionale'],a:'Mezzaluna Fertile (Medio Oriente)'},
  {s:'Preistoria',t:'Neolitico',b:'understand',
   c:'Perché la sedentarizzazione neolitica portò a un aumento della popolazione rispetto al Paleolitico?',
   o:['Una produzione alimentare più stabile e prevedibile consentì di sfamare più persone nello stesso luogo','Le malattie diminuirono drasticamente con la vita stabile','La guerra cessò con l\'abbandono del nomadismo','Gli esseri umani vissero più a lungo grazie al clima più caldo'],a:'Una produzione alimentare più stabile e prevedibile consentì di sfamare più persone nello stesso luogo'},
  {s:'Preistoria',t:'Neolitico',b:'understand',
   c:'Come cambiò la struttura sociale con la nascita dei villaggi neolitici rispetto alle bande paleolitiche?',
   o:['Emersero ruoli specializzati, gerarchie sociali e forme elementari di proprietà privata','La società divenne più egualitaria grazie alla condivisione del cibo','Sparirono i conflitti intercomunitari','La famiglia nucleare fu sostituita dalla famiglia allargata'],a:'Emersero ruoli specializzati, gerarchie sociali e forme elementari di proprietà privata'},
  {s:'Preistoria',t:'Neolitico',b:'apply',
   c:'Un villaggio neolitico subisce due raccolti fallimentari consecutivi. Quale conseguenza è più probabile?',
   o:['Migrazioni verso nuove terre, conflitti con vicini per le risorse o sperimentazione di nuove colture','Ritorno immediato al nomadismo dei cacciatori-raccoglitori','Sviluppo immediato dell\'irrigazione artificiale','Nessun impatto: le riserve alimentari erano sufficienti per anni'],a:'Migrazioni verso nuove terre, conflitti con vicini per le risorse o sperimentazione di nuove colture'},
  {s:'Preistoria',t:'Neolitico',b:'apply',
   c:'Un archeologo trova un sito con ceramiche, resti di cereali carbonizzati e ossa di bovini domestici. A quale periodo lo attribuisce?',
   o:['Neolitico','Paleolitico superiore','Età del Bronzo','Mesolitico'],a:'Neolitico'},
  {s:'Preistoria',t:'Neolitico',b:'analyze',
   c:'Quali vantaggi e svantaggi portò l\'agricoltura rispetto alla caccia-raccolta in termini di salute?',
   o:['Più calorie disponibili ma dieta meno varia e nuove malattie infettive legate alla vicinanza con gli animali','Solo vantaggi: più cibo e nessun rischio di infezioni','Solo svantaggi: dieta povera e lavoro più faticoso','Nessuna differenza significativa sulla salute delle popolazioni'],a:'Più calorie disponibili ma dieta meno varia e nuove malattie infettive legate alla vicinanza con gli animali'},
  {s:'Preistoria',t:'Neolitico',b:'analyze',
   c:'Perché la domesticazione degli animali è strettamente collegata allo sviluppo dell\'agricoltura nel Neolitico?',
   o:['Gli animali fornirono forza lavoro per arare, letame come fertilizzante e prodotti aggiuntivi come latte e lana','Gli animali proteggevano le colture dai predatori','Solo per ragioni religiose e simboliche','Gli animali erano coltivati come fonte principale di cibo, non le piante'],a:'Gli animali fornirono forza lavoro per arare, letame come fertilizzante e prodotti aggiuntivi come latte e lana'},
  {s:'Preistoria',t:'Neolitico',b:'evaluate',
   c:'La "rivoluzione neolitica" fu davvero una rivoluzione rapida o un processo graduale?',
   o:['Fu un processo graduale su millenni con esiti profondi, non una trasformazione improvvisa','Fu una rivoluzione rapida avvenuta in meno di un secolo in ogni regione','Fu solo un cambiamento climatico che obbligò le persone a coltivare','Non ci fu alcuna discontinuità: l\'agricoltura esisteva già nel Paleolitico'],a:'Fu un processo graduale su millenni con esiti profondi, non una trasformazione improvvisa'},
  {s:'Preistoria',t:'Neolitico',b:'create',
   c:'Se la coltivazione del frumento non fosse mai stata possibile in Europa, quale alternativa colturale avrebbe potuto diventare la base dell\'alimentazione?',
   o:['Legumi, radici commestibili e alberi da frutto come base alimentare principale','Il riso, anche se non adatto al clima europeo','La carne, tornando al puro nomadismo','Il mais, importato dalle Americhe molto prima del previsto'],a:'Legumi, radici commestibili e alberi da frutto come base alimentare principale'},

  // ── Età del Bronzo ─────────────────────────────────────────────────
  {s:'Preistoria',t:'Età del Bronzo',b:'remember',
   c:'Di quali due metalli è composta la lega del bronzo?',
   o:['Rame e stagno','Ferro e carbone','Rame e zinco','Oro e piombo'],a:'Rame e stagno'},
  {s:'Preistoria',t:'Età del Bronzo',b:'remember',
   c:'Intorno a quale data si colloca convenzionalmente il "collasso dell\'Età del Bronzo" nel Mediterraneo?',
   o:['1200 a.C.','3300 a.C.','500 a.C.','2000 a.C.'],a:'1200 a.C.'},
  {s:'Preistoria',t:'Età del Bronzo',b:'understand',
   c:'Perché la scarsità relativa dello stagno favorì lo sviluppo di reti commerciali a lunga distanza nell\'Età del Bronzo?',
   o:['Lo stagno era raro e geograficamente distante dal rame, creando dipendenza commerciale tra regioni lontane','Lo stagno era prezioso come l\'oro e veniva accumulato come riserva','Il bronzo era così pesante da richiedere molti trasportatori','Le rotte commerciali erano già consolidate dal Paleolitico'],a:'Lo stagno era raro e geograficamente distante dal rame, creando dipendenza commerciale tra regioni lontane'},
  {s:'Preistoria',t:'Età del Bronzo',b:'understand',
   c:'Cosa indica la presenza di tombe con ricchi corredi in bronzo rispetto a tombe più semplici dello stesso periodo?',
   o:['L\'emergere di élite sociali e disuguaglianze economiche già nell\'Età del Bronzo','Differenze religiose tra gruppi della stessa comunità','Differenti fasi cronologiche della stessa civiltà','La distinzione tra guerrieri e sacerdoti senza implicazioni economiche'],a:'L\'emergere di élite sociali e disuguaglianze economiche già nell\'Età del Bronzo'},
  {s:'Preistoria',t:'Età del Bronzo',b:'apply',
   c:'Un esercito con armi di bronzo affronta guerrieri armati solo di pietra. Quale vantaggio tattico decisivo ha?',
   o:['Armi più dure e affilate, resistenti agli urti, che possono essere riaffilate e riparate','Solo un vantaggio psicologico: la lucentezza del bronzo intimoriva il nemico','Nessun vantaggio reale: la pietra è più abbondante e quindi più efficace','Il bronzo è più leggero della pietra, garantendo più velocità'],a:'Armi più dure e affilate, resistenti agli urti, che possono essere riaffilate e riparate'},
  {s:'Preistoria',t:'Età del Bronzo',b:'apply',
   c:'Özi, la mummia del Similaun, portava con sé un\'ascia di rame. Cosa ci dice questo sull\'epoca in cui visse?',
   o:['Visse nel periodo di transizione tra Neolitico ed Età del Bronzo (Calcolitico), quando il rame era già usato ma il bronzo non ancora diffuso','Visse nel pieno dell\'Età del Bronzo, quando il rame era il metallo più comune','Visse nel Paleolitico, poiché il rame era il primo metallo lavorato','Visse nell\'Età del Ferro, poiché portava anche oggetti in ferro'],a:'Visse nel periodo di transizione tra Neolitico ed Età del Bronzo (Calcolitico), quando il rame era già usato ma il bronzo non ancora diffuso'},
  {s:'Preistoria',t:'Età del Bronzo',b:'analyze',
   c:'Quali fattori concorsero al collasso delle civiltà dell\'Età del Bronzo mediterranea intorno al 1200 a.C.?',
   o:['Una combinazione di invasioni dei "Popoli del Mare", siccità, crisi delle rotte commerciali e instabilità interna','Solo le invasioni militari dei Popoli del Mare','Esclusivamente il cambiamento climatico senza fattori umani','La scoperta del ferro che rese obsolete tutte le strutture del Bronzo'],a:'Una combinazione di invasioni dei "Popoli del Mare", siccità, crisi delle rotte commerciali e instabilità interna'},
  {s:'Preistoria',t:'Età del Bronzo',b:'analyze',
   c:'Perché le civiltà palatine dell\'Egeo (Micene, Cnosso) erano economicamente interdipendenti?',
   o:['Commerciavano ceramiche, olio, cereali e materie prime attraverso il Mediterraneo orientale, con dipendenza reciproca','Erano indipendenti: ogni palazzo produceva tutto il necessario senza commerciare','Si coordinavano solo per le guerre contro i Fenici','La scrittura Lineare B dimostrava una burocrazia comune centralizzata'],a:'Commerciavano ceramiche, olio, cereali e materie prime attraverso il Mediterraneo orientale, con dipendenza reciproca'},
  {s:'Preistoria',t:'Età del Bronzo',b:'evaluate',
   c:'Quale aspetto del collasso dell\'Età del Bronzo ebbe le conseguenze più durature per la civiltà mediterranea?',
   o:['La distruzione delle rotte commerciali e la perdita della scrittura per secoli (i "secoli bui" greci)','La scomparsa della metallurgia del bronzo','La fine del commercio di spezie','La distruzione delle piramidi egizie'],a:'La distruzione delle rotte commerciali e la perdita della scrittura per secoli (i "secoli bui" greci)'},
  {s:'Preistoria',t:'Età del Bronzo',b:'create',
   c:'Se lo stagno fosse stato abbondante in ogni regione del Mediterraneo, come sarebbe cambiato lo sviluppo delle prime civiltà?',
   o:['Minore interdipendenza commerciale tra regioni, con sviluppo metallurgico locale più autonomo e meno scambio culturale','Le civiltà si sarebbero sviluppate più velocemente grazie al bronzo abbondante','Non ci sarebbe stato alcun effetto significativo sulla storia','Le civiltà si sarebbero unite in un unico grande impero'],a:'Minore interdipendenza commerciale tra regioni, con sviluppo metallurgico locale più autonomo e meno scambio culturale'},

  // ── Età del Ferro ──────────────────────────────────────────────────
  {s:'Preistoria',t:'Età del Ferro',b:'remember',
   c:'Quale popolo anatolico fu tra i primi a padroneggiare la lavorazione del ferro, rendendola un segreto strategico?',
   o:['Gli Ittiti','I Fenici','I Greci','I Persiani'],a:'Gli Ittiti'},
  {s:'Preistoria',t:'Età del Ferro',b:'remember',
   c:'La cultura di Hallstatt (800–450 a.C.) è associata a quale popolo preistorico europeo?',
   o:['I Celti della prima Età del Ferro','I Germani del Nord','I Greci di Magna Grecia','I Fenici in Spagna'],a:'I Celti della prima Età del Ferro'},
  {s:'Preistoria',t:'Età del Ferro',b:'understand',
   c:'Perché il ferro soppiantò il bronzo come materiale principale per armi e utensili?',
   o:['Il ferro era molto più abbondante geograficamente del bronzo, rendendolo accessibile a più popoli','Il ferro era più leggero del bronzo e quindi preferito dai guerrieri','Il ferro non si arrugginiva, a differenza del bronzo','Il ferro aveva un aspetto esteticamente superiore'],a:'Il ferro era molto più abbondante geograficamente del bronzo, rendendolo accessibile a più popoli'},
  {s:'Preistoria',t:'Età del Ferro',b:'understand',
   c:'Come cambiò l\'organizzazione militare in Europa con la diffusione delle armi di ferro?',
   o:['La guerra si "democratizzò": anche soldati di ceto inferiore potevano permettersi armi efficienti','Solo l\'élite aristocratica poteva permettersi il ferro, aumentando le disuguaglianze','Le guerre cessarono perché il ferro era troppo pesante da trasportare','La cavalleria scomparve a favore della fanteria pesante'],a:'La guerra si "democratizzò": anche soldati di ceto inferiore potevano permettersi armi efficienti'},
  {s:'Preistoria',t:'Età del Ferro',b:'apply',
   c:'Una tribù celtica con armi di ferro affronta vicini armati di bronzo. Quale vantaggio strategico decisivo possiede?',
   o:['Armi più dure, affilabili ripetutamente, e più facili da rimpiazzare grazie alla diffusione locale del minerale','Solo un vantaggio psicologico legato alla novità del materiale','Nessun vantaggio: il bronzo era superiore in durezza','Le armi di ferro erano più leggere e quindi i guerrieri erano più veloci'],a:'Armi più dure, affilabili ripetutamente, e più facili da rimpiazzare grazie alla diffusione locale del minerale'},
  {s:'Preistoria',t:'Età del Ferro',b:'apply',
   c:'Un contadino dell\'Età del Ferro sostituisce il suo aratro di legno con uno dotato di punta in ferro. Quale beneficio pratico ne ricava?',
   o:['Può arare terreni più duri e profondi, aumentando la produttività agricola','L\'aratro diventa più leggero e facile da trasportare','Il ferro fertilizza automaticamente il suolo','Può lavorare più velocemente grazie al peso maggiore'],a:'Può arare terreni più duri e profondi, aumentando la produttività agricola'},
  {s:'Preistoria',t:'Età del Ferro',b:'analyze',
   c:'Perché l\'Età del Ferro favorì la nascita di stati più estesi rispetto all\'Età del Bronzo?',
   o:['La disponibilità diffusa del ferro permise eserciti più grandi e una produzione agricola più intensa, sostenendo popolazioni e strutture statali più ampie','Il ferro era più costoso del bronzo, concentrando il potere nelle mani di pochi re potenti','L\'Età del Ferro coincise con un lungo periodo di pace che favorì la formazione di stati','Il ferro era più leggero, permettendo eserciti più mobili'],a:'La disponibilità diffusa del ferro permise eserciti più grandi e una produzione agricola più intensa, sostenendo popolazioni e strutture statali più ampie'},
  {s:'Preistoria',t:'Età del Ferro',b:'analyze',
   c:'Quali differenze strutturali esistono tra la cultura di Hallstatt e quella di La Tène nell\'Età del Ferro celtica?',
   o:['Hallstatt più orientata al commercio di sale e ambra; La Tène più guerriera, con arte curvilinea più elaborata e maggiore espansionismo','Hallstatt era la fase più tarda; La Tène la più antica','Non ci sono differenze sostanziali: sono la stessa cultura in periodi diversi','Hallstatt era celtica; La Tène era germanica'],a:'Hallstatt più orientata al commercio di sale e ambra; La Tène più guerriera, con arte curvilinea più elaborata e maggiore espansionismo'},
  {s:'Preistoria',t:'Età del Ferro',b:'evaluate',
   c:'Quale fu la conseguenza più importante della diffusione del ferro per le società agricole del I millennio a.C.?',
   o:['L\'aumento della produttività agricola grazie agli aratri in ferro, che permise di nutrire popolazioni più grandi e sostenere città più complesse','La produzione di armi superiori che causò guerre più distruttive','La scomparsa del commercio a lunga distanza perché ogni regione era autosufficiente','La formazione di grandi monarchie teocratiche grazie al controllo del ferro'],a:'L\'aumento della produttività agricola grazie agli aratri in ferro, che permise di nutrire popolazioni più grandi e sostenere città più complesse'},
  {s:'Preistoria',t:'Età del Ferro',b:'create',
   c:'Se il ferro non fosse mai stato scoperto, come si sarebbe potuta evolvere la civiltà romana senza questo materiale?',
   o:['Roma avrebbe avuto un\'espansione molto più limitata, dipendendo da un\'industria del bronzo costosa e difficile da scalare per eserciti di massa','Roma si sarebbe espansa comunque, usando solo soldati con armi di bronzo più pesanti','Roma avrebbe sviluppato alternative come la pietra lavorata per le armi','Il ferro era irrilevante: fu la tattica militare a fare la differenza'],a:'Roma avrebbe avuto un\'espansione molto più limitata, dipendendo da un\'industria del bronzo costosa e difficile da scalare per eserciti di massa'},
];

async function main() {
  const token = await getToken();
  let ok=0, fail=0;
  for (const q of Q) {
    const res = await fetch(`${PB_URL}/api/collections/Question/records`, {
      method:'POST', headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},
      body: JSON.stringify({subject:q.s,topic:q.t,content:q.c,options:q.o,correct_answer:q.a,bloom_level:q.b,owner:OWNER}),
    });
    if (res.ok) { ok++; process.stdout.write(`\r  ${ok}/${Q.length}`); }
    else { fail++; console.error('\nFAIL', q.c.slice(0,40), await res.text()); }
  }
  console.log(`\nPreistoria: ${ok} ok, ${fail} fail`);
}
main().catch(console.error);
